--------------------------------------------------------
--  File created - Thursday-September-08-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ALERTAS
--------------------------------------------------------

  CREATE TABLE "DB12016"."ALERTAS" 
   (	"ID_ALERTA" NUMBER(12,0), 
	"ALERTA" VARCHAR2(50 BYTE), 
	"ID_EMAIL" NUMBER(12,0), 
	"ID_TELEFONO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAJA_RECEPTORA
--------------------------------------------------------

  CREATE TABLE "DB12016"."CAJA_RECEPTORA" 
   (	"ID_CAJA_RECEPTORA" NUMBER(12,0), 
	"SALDO_INICIAL" FLOAT(126), 
	"SALDO_FINAL" FLOAT(126), 
	"FECHA" DATE, 
	"HORA_APERTURA" TIMESTAMP (6), 
	"HORA_CIERRE" TIMESTAMP (6), 
	"ID_TURNO" NUMBER(12,0), 
	"ID_VENTA" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."CATEGORIA_PRODUCTO" 
   (	"ID_TIPO_PRODUCTO" NUMBER(12,0), 
	"CATEGORIA_PRODUCTO" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTENIDO_ENVIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."CONTENIDO_ENVIO" 
   (	"ID_CONTENIDO_ENVIO" NUMBER(12,0), 
	"CONTENIDO" VARCHAR2(40 BYTE), 
	"ID_ENVIO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DESTINATARIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."DESTINATARIO" 
   (	"ID_DESTINATARIO" NUMBER(12,0), 
	"ID_EMPRESA" NUMBER(12,0), 
	"ID_USUARIO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_ENVIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."DETALLE_ENVIO" 
   (	"ID_DETALLE_ENVIO" NUMBER(12,0), 
	"FECHA_ENVIO" DATE, 
	"EMBALAJE" VARCHAR2(50 BYTE), 
	"PESO_TOTAL" NUMBER(12,0), 
	"VALOR_TRANSPORTE" NUMBER(12,0), 
	"COSTO_ESTIMADO" NUMBER(12,0), 
	"REFERENCIA" VARCHAR2(90 BYTE), 
	"ID_PAQUETE" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA
--------------------------------------------------------

  CREATE TABLE "DB12016"."DETALLE_FACTURA" 
   (	"ID_DETALLE_FACTURA" NUMBER(12,0), 
	"PRECIO" NUMBER(12,0), 
	"DESCUENTO" NUMBER(12,0), 
	"TOTAL" NUMBER(12,0), 
	"ID_FACTURA" NUMBER(12,0), 
	"ID_PRODUCTO" NUMBER(12,0), 
	"ID_EMPRESA" NUMBER(12,0), 
	"ID_USUARIO" NUMBER(12,0), 
	"ID_PROMOCION" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEVOLUCIONES
--------------------------------------------------------

  CREATE TABLE "DB12016"."DEVOLUCIONES" 
   (	"ID_DEVOLUCIONES" NUMBER(12,0), 
	"DEVOLUCION" VARCHAR2(65 BYTE), 
	"DESCRIPCION" VARCHAR2(75 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIRECCION
--------------------------------------------------------

  CREATE TABLE "DB12016"."DIRECCION" 
   (	"ID_DIRECCION" NUMBER(12,0), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMAIL
--------------------------------------------------------

  CREATE TABLE "DB12016"."EMAIL" 
   (	"ID_EMAIL" NUMBER(12,0), 
	"DIRECCION_EMAIL" VARCHAR2(60 BYTE), 
	"EMPRESA_EMAIL" VARCHAR2(80 BYTE), 
	"ID_TIPO_EMAIL" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENVIOS
--------------------------------------------------------

  CREATE TABLE "DB12016"."ENVIOS" 
   (	"ID_ENVIO" NUMBER(12,0), 
	"ENVIO" VARCHAR2(45 BYTE), 
	"FECHA" DATE, 
	"ID_DETALLE_ENVIO" NUMBER(12,0), 
	"ID_DESTINATARIO" NUMBER(12,0), 
	"ID_SERVICIO" NUMBER(12,0), 
	"ID_MANEJO" NUMBER(12,0), 
	"ID_ALERTA" NUMBER(12,0), 
	"ID_USUARIO" NUMBER(12,0), 
	"ID_DIRECCION" NUMBER(12,0), 
	"ID_PRODUCTO" NUMBER(12,0), 
	"ID_DEVOLUCIONES" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "DB12016"."FACTURA" 
   (	"ID_FACTURA" NUMBER(12,0), 
	"FECHA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GARANTIA
--------------------------------------------------------

  CREATE TABLE "DB12016"."GARANTIA" 
   (	"ID_GARANTIA" NUMBER(12,0), 
	"GARANTIA" VARCHAR2(60 BYTE), 
	"FECHA_INICIA_G" DATE, 
	"FECHA_FIN_G" DATE, 
	"DESCRIPCION" VARCHAR2(60 BYTE), 
	"OBSERVACIONES" VARCHAR2(190 BYTE), 
	"ID_TIPO_GARANTIA" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table IMPUESTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."IMPUESTO" 
   (	"ID_IMPUESTO" NUMBER(12,0), 
	"IMPUESTO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KARDEX
--------------------------------------------------------

  CREATE TABLE "DB12016"."KARDEX" 
   (	"ID_KARDEX" NUMBER(12,0), 
	"PRECIO_COMPRA" FLOAT(126), 
	"PRECIO_VENTA" FLOAT(126), 
	"STOCK_ANTERIOR" NUMBER(12,0), 
	"STOCK_ACTUAL" NUMBER(12,0), 
	"TIPO" VARCHAR2(10 BYTE), 
	"CANTIDAD" NUMBER(12,0), 
	"ID_MOVIMIENTO" NUMBER(12,0), 
	"ID_PROVEEDOR" NUMBER(12,0), 
	"ID_PRODUCTO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANEJO
--------------------------------------------------------

  CREATE TABLE "DB12016"."MANEJO" 
   (	"ID_MANEJO" NUMBER(12,0), 
	"MANEJO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MAN_ESTADOS
--------------------------------------------------------

  CREATE TABLE "DB12016"."MAN_ESTADOS" 
   (	"ID_ESTADO" NUMBER(12,0), 
	"ESTADO" VARCHAR2(45 BYTE), 
	"ID_TIPO_ESTADO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MODO_PAGO
--------------------------------------------------------

  CREATE TABLE "DB12016"."MODO_PAGO" 
   (	"ID_MODO_PAGO" NUMBER(12,0), 
	"MODO_PAGO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."MOVIMIENTO" 
   (	"ID_MOVIMIENTO" NUMBER(12,0), 
	"FACTURA" VARCHAR2(60 BYTE), 
	"FECHA_FACTURA" DATE, 
	"FECHA_SALIDA" TIMESTAMP (6), 
	"RESPONSABLE" VARCHAR2(60 BYTE), 
	"TIPO_MOVIMIENTO" VARCHAR2(60 BYTE), 
	"MOVIMIENTO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NEGOCIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."NEGOCIO" 
   (	"ID_EMPRESA" NUMBER(12,0), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_EMAIL" NUMBER(12,0), 
	"ID_TELEFONO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGO
--------------------------------------------------------

  CREATE TABLE "DB12016"."PAGO" 
   (	"ID_PAGO" NUMBER(12,0), 
	"FECHA" TIMESTAMP (6), 
	"MONTO_TOTAL" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAIS
--------------------------------------------------------

  CREATE TABLE "DB12016"."PAIS" 
   (	"ID_PAIS" NUMBER(12,0), 
	"PAIS" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAQUETE
--------------------------------------------------------

  CREATE TABLE "DB12016"."PAQUETE" 
   (	"ID_PAQUETE" NUMBER(12,0), 
	"PAQUETE" VARCHAR2(60 BYTE), 
	"ID_TIPO_PAQUETE" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(12,0), 
	"NOMBRE_PRODUCTO" VARCHAR2(40 BYTE), 
	"CANTIDAD_MINIMA" NUMBER(12,0), 
	"CANTIDAD_MAXIMA" NUMBER(12,0), 
	"EXISTENCIA_PRODUCTO" NUMBER(12,0), 
	"PRECIO_COSTO_PRODUCTO" NUMBER(12,0), 
	"PRECIO_VENTA_PRODUCTO" NUMBER(12,0), 
	"ACTIVO_PRODUCTO" NUMBER(12,0), 
	"ID_UNIDAD_MEDIDA" NUMBER(12,0), 
	"ID_TIPO_PRODUCTO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROMOCION
--------------------------------------------------------

  CREATE TABLE "DB12016"."PROMOCION" 
   (	"ID_PROMOCION" NUMBER(12,0), 
	"TIPO" VARCHAR2(80 BYTE), 
	"COSTO" FLOAT(126), 
	"INICIO_PROMO" DATE, 
	"FIN_PROMO" DATE, 
	"ESTADO_PROMO" VARCHAR2(30 BYTE), 
	"DESCRIP_PROMO" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "DB12016"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(12,0), 
	"NOMBRE_EMPRESA" VARCHAR2(50 BYTE), 
	"ID_DIRECCION" NUMBER(12,0), 
	"ID_EMAIL" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REMITENTE
--------------------------------------------------------

  CREATE TABLE "DB12016"."REMITENTE" 
   (	"ID_REMITENTE" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REPARACIONES
--------------------------------------------------------

  CREATE TABLE "DB12016"."REPARACIONES" 
   (	"ID_REPARACION" NUMBER(12,0), 
	"REPARACION" VARCHAR2(60 BYTE), 
	"DESCRIPCION" VARCHAR2(60 BYTE), 
	"DESCRIPCION2" VARCHAR2(190 BYTE), 
	"COSTO" NUMBER(12,0), 
	"FECHA_RECIBO" DATE, 
	"FECHA_ENTREGA" DATE, 
	"ID_TIPO_REPARACION" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."SERVICIO" 
   (	"ID_SERVICIO" NUMBER(12,0), 
	"SERVICIO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TELEFONO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TELEFONO" 
   (	"ID_TELEFONO" NUMBER(12,0), 
	"NUMERO_TELEFONO" VARCHAR2(50 BYTE), 
	"EMPRESA_TELEFONICA" VARCHAR2(50 BYTE), 
	"ID_TIPO_TELEFONO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_DOCUMENTO" 
   (	"ID_TIPO_DOCUMENTO" NUMBER(12,0), 
	"DOCUMENTO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_EMAIL
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_EMAIL" 
   (	"ID_TIPO_EMAIL" NUMBER(12,0), 
	"TIPO_EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_ESTADO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_ESTADO" 
   (	"ID_TIPO_ESTADO" NUMBER(12,0), 
	"TIPO_ESTADO" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_GARANTIA
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_GARANTIA" 
   (	"ID_TIPO_GARANTIA" NUMBER(12,0), 
	"TIPO_GARANTIA" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_IMPUESTO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_IMPUESTO" 
   (	"ID_TIPO_IMPUESTO" NUMBER(12,0), 
	"TIPO_IMPUESTO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_PAQUETE
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_PAQUETE" 
   (	"ID_TIPO_PAQUETE" NUMBER(12,0), 
	"TIPO_PAQUETE" VARCHAR2(60 BYTE), 
	"LARGO" NUMBER(12,0), 
	"ANCHO" NUMBER(12,0), 
	"PROFUNDIDA" NUMBER(12,0), 
	"PESO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_REPARACION
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_REPARACION" 
   (	"ID_TIPO_REPARACION" NUMBER(12,0), 
	"REPARACION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_TELEFONO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_TELEFONO" 
   (	"ID_TIPO_TELEFONO" NUMBER(12,0), 
	"TIPO_TELEFONO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_TURNO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_TURNO" 
   (	"ID_TIPO_TURNO" NUMBER(12,0), 
	"TIPO_TURNO" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_USUARIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_USUARIO" 
   (	"ID_TIPO_USUARIO" NUMBER(12,0), 
	"TIPO_USUARIO" VARCHAR2(60 BYTE), 
	"DESCRIPCION" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_VENTA
--------------------------------------------------------

  CREATE TABLE "DB12016"."TIPO_VENTA" 
   (	"ID_TIPO_VENTA" NUMBER(12,0), 
	"TIPO_VENTA" VARCHAR2(60 BYTE), 
	"DESCRIP_VENTA" VARCHAR2(120 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TURNO
--------------------------------------------------------

  CREATE TABLE "DB12016"."TURNO" 
   (	"ID_TURNO" NUMBER(12,0), 
	"FECHA" DATE, 
	"HORA" TIMESTAMP (6), 
	"ID_USUARIO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table UNIDAD_MEDIDA
--------------------------------------------------------

  CREATE TABLE "DB12016"."UNIDAD_MEDIDA" 
   (	"ID_UNIDAD_MEDIDA" NUMBER(12,0), 
	"NUMBER_UNIDAD_MEDIDA" VARCHAR2(20 BYTE), 
	"CANTIDAD_UNIDAD_MEDIDA" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "DB12016"."USUARIO" 
   (	"ID_USUARIO" NUMBER(12,0), 
	"LOGIN" VARCHAR2(60 BYTE), 
	"PASSWORD" VARCHAR2(60 BYTE), 
	"FECHA_ALTA" DATE, 
	"FECHA_BAJA" DATE, 
	"ID_TIPO_USUARIO" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table VENTA
--------------------------------------------------------

  CREATE TABLE "DB12016"."VENTA" 
   (	"ID_VENTA" NUMBER(12,0), 
	"ID_TIPO_VENTA" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DB12016.ALERTAS
SET DEFINE OFF;
REM INSERTING into DB12016.CAJA_RECEPTORA
SET DEFINE OFF;
REM INSERTING into DB12016.CATEGORIA_PRODUCTO
SET DEFINE OFF;
REM INSERTING into DB12016.CONTENIDO_ENVIO
SET DEFINE OFF;
REM INSERTING into DB12016.DESTINATARIO
SET DEFINE OFF;
REM INSERTING into DB12016.DETALLE_ENVIO
SET DEFINE OFF;
REM INSERTING into DB12016.DETALLE_FACTURA
SET DEFINE OFF;
REM INSERTING into DB12016.DEVOLUCIONES
SET DEFINE OFF;
REM INSERTING into DB12016.DIRECCION
SET DEFINE OFF;
REM INSERTING into DB12016.EMAIL
SET DEFINE OFF;
REM INSERTING into DB12016.ENVIOS
SET DEFINE OFF;
REM INSERTING into DB12016.FACTURA
SET DEFINE OFF;
REM INSERTING into DB12016.GARANTIA
SET DEFINE OFF;
REM INSERTING into DB12016.IMPUESTO
SET DEFINE OFF;
REM INSERTING into DB12016.KARDEX
SET DEFINE OFF;
REM INSERTING into DB12016.MANEJO
SET DEFINE OFF;
REM INSERTING into DB12016.MAN_ESTADOS
SET DEFINE OFF;
REM INSERTING into DB12016.MODO_PAGO
SET DEFINE OFF;
REM INSERTING into DB12016.MOVIMIENTO
SET DEFINE OFF;
REM INSERTING into DB12016.NEGOCIO
SET DEFINE OFF;
REM INSERTING into DB12016.PAGO
SET DEFINE OFF;
REM INSERTING into DB12016.PAIS
SET DEFINE OFF;
REM INSERTING into DB12016.PAQUETE
SET DEFINE OFF;
REM INSERTING into DB12016.PRODUCTO
SET DEFINE OFF;
REM INSERTING into DB12016.PROMOCION
SET DEFINE OFF;
REM INSERTING into DB12016.PROVEEDOR
SET DEFINE OFF;
REM INSERTING into DB12016.REMITENTE
SET DEFINE OFF;
REM INSERTING into DB12016.REPARACIONES
SET DEFINE OFF;
REM INSERTING into DB12016.SERVICIO
SET DEFINE OFF;
REM INSERTING into DB12016.TELEFONO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_DOCUMENTO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_EMAIL
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_ESTADO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_GARANTIA
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_IMPUESTO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_PAQUETE
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_REPARACION
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_TELEFONO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_TURNO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_USUARIO
SET DEFINE OFF;
REM INSERTING into DB12016.TIPO_VENTA
SET DEFINE OFF;
REM INSERTING into DB12016.TURNO
SET DEFINE OFF;
REM INSERTING into DB12016.UNIDAD_MEDIDA
SET DEFINE OFF;
REM INSERTING into DB12016.USUARIO
SET DEFINE OFF;
REM INSERTING into DB12016.VENTA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ID_CAJA_RECEPTORA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_CAJA_RECEPTORA" ON "DB12016"."CAJA_RECEPTORA" ("ID_CAJA_RECEPTORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PRODUCTO" ON "DB12016"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_KARDEX
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_KARDEX" ON "DB12016"."KARDEX" ("ID_KARDEX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_DIRECCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_DIRECCION" ON "DB12016"."DIRECCION" ("ID_DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TURNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TURNO" ON "DB12016"."TURNO" ("ID_TURNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PROVEEDOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PROVEEDOR" ON "DB12016"."PROVEEDOR" ("ID_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PROMOCION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PROMOCION" ON "DB12016"."PROMOCION" ("ID_PROMOCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_TIPO_USUARIO" ON "DB12016"."TIPO_USUARIO" ("ID_TIPO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_DETALLE_FACTURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_DETALLE_FACTURA" ON "DB12016"."DETALLE_FACTURA" ("ID_DETALLE_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_MOVIMIENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_MOVIMIENTO" ON "DB12016"."MOVIMIENTO" ("ID_MOVIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_PRODUCTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_PRODUCTO" ON "DB12016"."CATEGORIA_PRODUCTO" ("ID_TIPO_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_PAQUETE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_PAQUETE" ON "DB12016"."TIPO_PAQUETE" ("ID_TIPO_PAQUETE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_MODO_PAGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_MODO_PAGO" ON "DB12016"."MODO_PAGO" ("ID_MODO_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_VENTA" ON "DB12016"."VENTA" ("ID_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_DOCUMENTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_DOCUMENTO" ON "DB12016"."TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_GARANTIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_GARANTIA" ON "DB12016"."GARANTIA" ("ID_GARANTIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_FACTURA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_FACTURA" ON "DB12016"."FACTURA" ("ID_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_VENTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_VENTA" ON "DB12016"."TIPO_VENTA" ("ID_TIPO_VENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_REPARACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_REPARACION" ON "DB12016"."TIPO_REPARACION" ("ID_TIPO_REPARACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_ESTADO" ON "DB12016"."TIPO_ESTADO" ("ID_TIPO_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PAQUETE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PAQUETE" ON "DB12016"."PAQUETE" ("ID_PAQUETE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ENVIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_ENVIO" ON "DB12016"."ENVIOS" ("ID_ENVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_EMAIL" ON "DB12016"."EMAIL" ("ID_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_TELEFONO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_TELEFONO" ON "DB12016"."TIPO_TELEFONO" ("ID_TIPO_TELEFONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_IMPUESTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_IMPUESTO" ON "DB12016"."IMPUESTO" ("ID_IMPUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_SERVICIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_SERVICIO" ON "DB12016"."SERVICIO" ("ID_SERVICIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PAGO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PAGO" ON "DB12016"."PAGO" ("ID_PAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ESTADO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_ESTADO" ON "DB12016"."MAN_ESTADOS" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_DESTINATARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_DESTINATARIO" ON "DB12016"."DESTINATARIO" ("ID_DESTINATARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_DETALLE_ENVIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_DETALLE_ENVIO" ON "DB12016"."DETALLE_ENVIO" ("ID_DETALLE_ENVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_DEVOLUCIONES
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_DEVOLUCIONES" ON "DB12016"."DEVOLUCIONES" ("ID_DEVOLUCIONES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_PAIS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_PAIS" ON "DB12016"."PAIS" ("ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_REMITENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_REMITENTE" ON "DB12016"."REMITENTE" ("ID_REMITENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_UNIDAD_MEDIDA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_UNIDAD_MEDIDA" ON "DB12016"."UNIDAD_MEDIDA" ("ID_UNIDAD_MEDIDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_USUARIO" ON "DB12016"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_MANEJO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_MANEJO" ON "DB12016"."MANEJO" ("ID_MANEJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_TURNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_TURNO" ON "DB12016"."TIPO_TURNO" ("ID_TIPO_TURNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TELEFONO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TELEFONO" ON "DB12016"."TELEFONO" ("ID_TELEFONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_GARANTIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_TIPO_GARANTIA" ON "DB12016"."TIPO_GARANTIA" ("ID_TIPO_GARANTIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_EMAIL" ON "DB12016"."TIPO_EMAIL" ("ID_TIPO_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_CONTENIDO_ENVIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_CONTENIDO_ENVIO" ON "DB12016"."CONTENIDO_ENVIO" ("ID_CONTENIDO_ENVIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_ALERTA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_ALERTA" ON "DB12016"."ALERTAS" ("ID_ALERTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_REPARACION
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_REPARACION" ON "DB12016"."REPARACIONES" ("ID_REPARACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_EMPRESA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_EMPRESA" ON "DB12016"."NEGOCIO" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ID_TIPO_IMPUESTO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DB12016"."PK_ID_TIPO_IMPUESTO" ON "DB12016"."TIPO_IMPUESTO" ("ID_TIPO_IMPUESTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DETALLE_ENVIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."DETALLE_ENVIO" ADD CONSTRAINT "PK_ID_DETALLE_ENVIO" PRIMARY KEY ("ID_DETALLE_ENVIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "DB12016"."PRODUCTO" ADD CONSTRAINT "PK_ID_PRODUCTO" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."SERVICIO" ADD CONSTRAINT "PK_ID_SERVICIO" PRIMARY KEY ("ID_SERVICIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPARACIONES
--------------------------------------------------------

  ALTER TABLE "DB12016"."REPARACIONES" ADD CONSTRAINT "PK_ID_REPARACION" PRIMARY KEY ("ID_REPARACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_IMPUESTO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_IMPUESTO" ADD CONSTRAINT "PK_ID_TIPO_IMPUESTO" PRIMARY KEY ("ID_TIPO_IMPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MAN_ESTADOS
--------------------------------------------------------

  ALTER TABLE "DB12016"."MAN_ESTADOS" ADD CONSTRAINT "PK_ID_ESTADO" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table IMPUESTO
--------------------------------------------------------

  ALTER TABLE "DB12016"."IMPUESTO" ADD CONSTRAINT "PK_ID_IMPUESTO" PRIMARY KEY ("ID_IMPUESTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEVOLUCIONES
--------------------------------------------------------

  ALTER TABLE "DB12016"."DEVOLUCIONES" ADD CONSTRAINT "PK_ID_DEVOLUCIONES" PRIMARY KEY ("ID_DEVOLUCIONES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ALERTAS
--------------------------------------------------------

  ALTER TABLE "DB12016"."ALERTAS" ADD CONSTRAINT "PK_ID_ALERTA" PRIMARY KEY ("ID_ALERTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_REPARACION
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_REPARACION" ADD CONSTRAINT "PK_ID_TIPO_REPARACION" PRIMARY KEY ("ID_TIPO_REPARACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "DB12016"."DETALLE_FACTURA" ADD CONSTRAINT "PK_ID_DETALLE_FACTURA" PRIMARY KEY ("ID_DETALLE_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CAJA_RECEPTORA
--------------------------------------------------------

  ALTER TABLE "DB12016"."CAJA_RECEPTORA" ADD CONSTRAINT "PK_ID_CAJA_RECEPTORA" PRIMARY KEY ("ID_CAJA_RECEPTORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MODO_PAGO
--------------------------------------------------------

  ALTER TABLE "DB12016"."MODO_PAGO" ADD CONSTRAINT "PK_ID_MODO_PAGO" PRIMARY KEY ("ID_MODO_PAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table UNIDAD_MEDIDA
--------------------------------------------------------

  ALTER TABLE "DB12016"."UNIDAD_MEDIDA" ADD CONSTRAINT "PK_ID_UNIDAD_MEDIDA" PRIMARY KEY ("ID_UNIDAD_MEDIDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMAIL
--------------------------------------------------------

  ALTER TABLE "DB12016"."EMAIL" ADD CONSTRAINT "PK_ID_EMAIL" PRIMARY KEY ("ID_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GARANTIA
--------------------------------------------------------

  ALTER TABLE "DB12016"."GARANTIA" ADD CONSTRAINT "PK_ID_GARANTIA" PRIMARY KEY ("ID_GARANTIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_USUARIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_USUARIO" ADD CONSTRAINT "PK_TIPO_USUARIO" PRIMARY KEY ("ID_TIPO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CONTENIDO_ENVIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."CONTENIDO_ENVIO" ADD CONSTRAINT "PK_ID_CONTENIDO_ENVIO" PRIMARY KEY ("ID_CONTENIDO_ENVIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KARDEX
--------------------------------------------------------

  ALTER TABLE "DB12016"."KARDEX" ADD CONSTRAINT "PK_ID_KARDEX" PRIMARY KEY ("ID_KARDEX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TELEFONO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TELEFONO" ADD CONSTRAINT "PK_ID_TELEFONO" PRIMARY KEY ("ID_TELEFONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENVIOS
--------------------------------------------------------

  ALTER TABLE "DB12016"."ENVIOS" ADD CONSTRAINT "PK_ID_ENVIO" PRIMARY KEY ("ID_ENVIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_VENTA
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_VENTA" ADD CONSTRAINT "PK_ID_TIPO_VENTA" PRIMARY KEY ("ID_TIPO_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "DB12016"."PROVEEDOR" ADD CONSTRAINT "PK_ID_PROVEEDOR" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "DB12016"."FACTURA" ADD CONSTRAINT "PK_ID_FACTURA" PRIMARY KEY ("ID_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOCION
--------------------------------------------------------

  ALTER TABLE "DB12016"."PROMOCION" ADD CONSTRAINT "PK_ID_PROMOCION" PRIMARY KEY ("ID_PROMOCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_TURNO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_TURNO" ADD CONSTRAINT "PK_ID_TIPO_TURNO" PRIMARY KEY ("ID_TIPO_TURNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIRECCION
--------------------------------------------------------

  ALTER TABLE "DB12016"."DIRECCION" ADD CONSTRAINT "PK_ID_DIRECCION" PRIMARY KEY ("ID_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REMITENTE
--------------------------------------------------------

  ALTER TABLE "DB12016"."REMITENTE" ADD CONSTRAINT "PK_ID_REMITENTE" PRIMARY KEY ("ID_REMITENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPO_DOCUMENTO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TIPO_DOCUMENTO" ADD CONSTRAINT "PK_ID_TIPO_DOCUMENTO" PRIMARY KEY ("ID_TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."USUARIO" ADD CONSTRAINT "PK_ID_USUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTA
--------------------------------------------------------

  ALTER TABLE "DB12016"."VENTA" ADD CONSTRAINT "PK_ID_VENTA" PRIMARY KEY ("ID_VENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TURNO
--------------------------------------------------------

  ALTER TABLE "DB12016"."TURNO" ADD CONSTRAINT "PK_ID_TURNO" PRIMARY KEY ("ID_TURNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DESTINATARIO
--------------------------------------------------------

  ALTER TABLE "DB12016"."DESTINATARIO" ADD CONSTRAINT "PK_ID_DESTINATARIO" PRIMARY KEY ("ID_DESTINATARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
